### ISSUE TITLE
Stop putting a tarball in the repo?

### ISSUE THREAD

**Issue by MatthewCroughan** [dagthomas/comfyui_dagthomas#13]
Are you trying to sneak some sort of virus in? What exactly is the reason you're putting a tarball inside of a git repository? Can you do your part in preventing things like this from happening again https://www.reddit.com/r/comfyui/comments/1dbls5n/psa_if_youve_used_the_comfyui_llmvision_node_from/ ?

**Comment by dagthomas** [comment]
Hey @MatthewCroughan - I think I just zipped down the content of the folder to move the project, and forgot to remove it again. It was just the zipped contents of the same folder. 

Have removed it now, thanks for the heads up!

**Comment by MatthewCroughan** [comment]
@dagthomas Thanks a lot!
