### ISSUE TITLE
Improvements - How to

### ISSUE THREAD

**Issue by scofano** [dagthomas/comfyui_dagthomas#16]
https://huggingface.co/spaces/gokaygokay/FLUX-Prompt-Generator - many good improvements here. 
Would it be possible to merge those improvements into this custom node?

**Comment by dagthomas** [comment]
Hi  @scofano 

This costom node is alreay more advanced than that. 
You can use gpt-4o-mini, gpt-4o, local ollama, phi3.5, you name it. 
I just havent been updating the readme :) But you should be able to do alot more, than in the huggingface space. 

The space is done really well tho, so props to gokaygokay for that.

**Comment by scofano** [comment]
Hi @dagthomas The custom node is wonderful, but I was getting too many males with female clothes and scenes without a character, with characters (I'm assuming flux takes the artist's name as a character and places it there). 

Also, I couldn't find proper male clothes on the list to set it as fixed. I found that workspace first, so I asked him if he could separate males from female settings, which he did. This way now prompts are doing fine but, of course, using a custom node instead of generating prompts from a space and pasting them into the UI, so I'm trying to find a way to replicate the same condition (if male, load male clothes) or customize the fields (using a Json file, maybe) so I can create the options I need. 

Is it possible the way it is now? (I'm a noob, just a regular user of comfyui, ex-A1111)

**Comment by dagthomas** [comment]
Oki, so this is the new family
![image](https://github.com/user-attachments/assets/89c23e6f-44f5-4d2f-bb37-abf8cbd797c4)

There are alot of nodes, and you can also chain them
![image](https://github.com/user-attachments/assets/bf402844-ffdc-4dcf-bc6c-28d40e125011)


Its currently also in beta, so I have not written anything down in detail yet. 

But you should have ALOT of flexibility!

You can also pipe that further into a gpt-4o-mini node to enhance the prompt: 
![image](https://github.com/user-attachments/assets/3cff0d18-a6e7-43c3-be5a-b2fb8964fa23)

or you can use the local ollama node if you want that: 
![image](https://github.com/user-attachments/assets/9d8f7eaa-07c2-48a2-bf67-37ebfbbfa4ba)


Or you could load random images from a folder, feed them into gpt vision (or ollama vision, or phi3.5 - all supported) and create a prompt based on images. 
![image](https://github.com/user-attachments/assets/c9bbceaf-4a84-4d89-aecd-6026bafa1ab7)


If you flip the switch for dynamic prompt, you can even use one of the pre-defined prompts I have enclosed to automagically add your LORA token to the mix: 
![image](https://github.com/user-attachments/assets/1e69febe-2963-426c-b308-56766006b05e)


I have also extracted all prompts from my 10.000 created prompts, and created a total random generator you just hook up and run. No need for gpt or local llama - you get totally random stuff: 
![image](https://github.com/user-attachments/assets/3db6b94a-adca-4853-8530-5a95a79bceb7)


And there is alot more as well, have never gotten as far as to document it :)

Here is the workflow I created the screenshots from
[apntest.json](https://github.com/user-attachments/files/16830214/apntest.json)

if you want to try the gpt workflows, set your key in the env with "set OPENAI_API_KEY=sk....." before you run comfyui. 

There is also a possibility to add your own custom folders within comfyui_dagthomas/data/next with your own properties, that will be loaded in comfyui with the other nodes.

Have a good time creating!

**Comment by scofano** [comment]
Wow! I didn't know it worked like this. This takes prompting into a whole new level! TY! 😃

Any ETA for the new version?

**Comment by dagthomas** [comment]
Yeah, it can do alot - you can also just load multiple of one node and pipe it multiple times also. 

Its out, just download latest and you are good to go :) I Just haven't written about it before because I am lazy when it actually gets to the documentation :) 

I create nodes that I want to use, and that fits my workflow, and I share it - hopefully someone will find it amusing aswell :)

**Comment by dagthomas** [comment]
Just do a search for "APNext" inside comfyui, and you will find everything.

There is also a latent generator to make it easier with creating sizes, just input either height or width or both - and it automates it
![image](https://github.com/user-attachments/assets/ad30b6b4-0e56-4c1d-8fe2-ab4e76f94f0d)

Here is a workflow:
[apnext_workflow.json](https://github.com/user-attachments/files/16830251/apnext_workflow.json)

**Comment by scofano** [comment]
Thanks a lot! I'm getting crazy good results now that I learned how to link them.
I have a question: what is the attributes toggle for?
`attributes: A boolean to toggle attribute inclusion (default: False) `
(I didn't understand the usage)

**Comment by dagthomas** [comment]
Good to hear!

So, the attributes is not documented anywhere, but lets take "feminine outfits"

![image](https://github.com/user-attachments/assets/1340927b-ab16-40b7-a11f-a0d5c7048be3)

For each type, there is additional attributes - so if you have attributes selected, it will enclose them in () and add them to the prompt for extra detail.

![image](https://github.com/user-attachments/assets/cf729baf-1871-484a-a0fa-a4f7941d0625)

So not every array has these choices, but some do :)

**Comment by scofano** [comment]
Thank you so much for all the explanation. I was able to create a new node based on that. 

There is one thing I'm trying to figure out, how to remove the unnecessary spaces ("s . a")from the prompt so I can get a more "natural" one. 

For example:  A photograph of a young woman with fat but pronounced features at a neon sign . Photo with hard light . She has grey-blue eyes and Medium Sleek and Straight with Blunt Bangs (Medium) hair , blond hair . Ambient lit by light behind . She has a nevisian nationality and she is holding hands on hips, elbows in . A dutch angle shot in the daybreak. 

I'm putting commas and dots as a pre prompt, attempting to create a correct phrase, but sometimes I get spaces and sometimes not. 

I know flux will work the same way, but it is more like to beautify the prompt kind of thing, and get more control, if possible.

**Comment by scofano** [comment]
I also noticed that the categories (from the .json files in the folder) follow the alphabetical order. Which is sometimes not the best result, as I can't get character's traits and camera angles/ambient in solid groups together. 
(I don't know if for the model it would make any difference, but I'm just trying to keep natural language).

**Comment by scofano** [comment]
(anyway, for the order, I'm adding numbers as a prefix)
