### ISSUE TITLE
【BUG】Small problem with "lighting" and "default tags"

### ISSUE THREAD

**Issue by amimi818** [dagthomas/comfyui_dagthomas#2]
a great job.

But there are two small problems:
1. it doesn't handle the "disabled lighting" situation, which leads to frequent wheelchair-bound characters:
'''
        lighting = kwargs.get('lighting', "").lower()
        if lighting == "random":
            selected_lighting = ", ".join(random.sample(self.LIGHTING, random.randint(2, 5)))
            components.append(selected_lighting)
        else:
            components.append(lighting)
'''
3. the "default tags" are invalid:
'''
        params = [
            ('subject', 'default_tags', self.DEFAULT_TAGS),
            ('roles', self.ROLES),
'''

**Comment by dagthomas** [comment]
Thnx for finding the bug, should be fixed in latest commit :)

**Comment by dagthomas** [comment]
I'll check the default tags problem this evening

**Comment by dagthomas** [comment]
Now its fixed!

**Comment by amimi818** [comment]
I was having some problems accessing github on my network, so the issue was being duplicated.

The new version fixed the problem, but the "default tags" became random. I changed it to the following, FYI.

        params = [
            ('subject' if kwargs.get('subject', '') else 'default_tags', DEFAULT_TAGS),
            ('roles', ROLES),
            ... ...
