### ISSUE TITLE
【Bug】A little nitpick about "lighting" and "default tags"

### ISSUE THREAD

**Issue by amimi818** [dagthomas/comfyui_dagthomas#3]
a great job.

But there are two small issues:
1. it doesn't handle the "disabled lighting" situation, which leads to frequent wheelchair-bound characters:
'''
        lighting = kwargs.get('lighting', "").lower()
        if lighting == "random":
            selected_lighting = ", ".join(random.sample(self.LIGHTING, random.randint(2, 5)))
            components.append(selected_lighting)
        else:
            components.append(lighting)
'''
2. the "default tags" is invalid:
'''
        params = [
            ('subject', 'default_tags', self.DEFAULT_TAGS),
            ('roles', self.ROLES),
'''

**Comment by dagthomas** [comment]
Did you get the latest version with git pull?

**Comment by dagthomas** [comment]
I have updated this code, should be working :)
