### ISSUE TITLE
Required input is missing

### ISSUE THREAD

**Issue by sborys-ai** [dagthomas/comfyui_dagthomas#5]
* PromptGenerator 1:
  - Required input is missing: seed
Output will be ignored

What "seed" is being referred to if there is no such field in the node and only one "string" output? 
Or do I not understand how to use this node?

**Comment by dagthomas** [comment]
You might have updated it, and seed was added to the project. Try deleting it and createing the node again. 
Just added so seed can be used as a return value, so you can use the seed generated by the prompt generator in the KSampler aswell: 
![image](https://github.com/dagthomas/comfyui_dagthomas/assets/4311672/e5404d5e-48e4-4da7-af1c-f5df9622dd6a)
