### ISSUE TITLE
issue when picking artform/phototype

### ISSUE THREAD

**Issue by endo9000** [dagthomas/comfyui_dagthomas#6]
hello. sorry if its not an issue. its also my first time writing one on github. 
i am not even sure how to describe it. 

so when i pick an artform which isnt photography the photo_type wont get added to the prompt. 
but when i pick photography and an phototype (for example front view) it looks like that its ignoring the phototype. 

what i am trying to do is testing all photographer with consistent settings but they seem inconsistent when picking the settings i picked. 

is it an issue with myself or the code? 

still nice work! a lot of fun playing with it.

**Comment by dagthomas** [comment]
Tnx for the feedback, I'll try to have a look at it as soon as I can :)

**Comment by endo9000** [comment]
thanks! 🙏 
i think maybe the photo_type also needs a weight. 
sometimes when having photography and front view selected i still get backshots and stuff. 
happens with other options too that i get generations which does not fit the selected type. 
ah! btw i use dreamshaperXL_turboDpmmpSDE idk if thats an issue.

here an example i just got. 🤓
![preview_00003_](https://github.com/dagthomas/comfyui_dagthomas/assets/153239801/82042112-d2f6-4007-b738-950802b1496b)

**Comment by dagthomas** [comment]
Get the latest version and try again now

**Comment by endo9000** [comment]
thanks! seems fixed.
now another one... thats a little one. 

''portrait photography of a young woman with ((curly hair)) at a hotel, realism , (bilaterally symmetrical:1.2), shot on Canon EOS 5D Mark IV with Canon EF 24-70mm f-2.8L II photo by Brooke DiDonato''

there is a space between the lighting setting and its comma separator. (realism , )

edit
when selecting random in photo_type it seems like its always defaulting to hero view. 
i did 20 gens in a row and always got hero view.

**Comment by dagthomas** [comment]
I'll check it out ASAP. I did some commits yesterday, but only have my phone to code on atm,will check over - make sure you are on the latest build.

**Comment by endo9000** [comment]
im always updating when session begins 👍🤓

**Comment by dagthomas** [comment]
![image](https://github.com/dagthomas/comfyui_dagthomas/assets/4311672/b13c0cbe-2dff-42f0-b8a4-5867af403913)

Try removing the "SDXL Auto Prompter" all together, and add it again. I have seen that stuff is cached or hangs even tho version is updated. 

I am getting different views atleast. "WORKS ON MY MACHIN!" :)

**Comment by dagthomas** [comment]
I mean just the node in your comfyui, just remove and readd it

**Comment by endo9000** [comment]
> I mean just the node in your comfyui, just remove and readd it

that did it for me. 🙏👍
