### ISSUE TITLE
Logic Questions

### ISSUE THREAD

**Issue by dxnxz** [dagthomas/comfyui_dagthomas#9]
Hi there! Thank you for your work!

I think some of the inputs are dependent upon each other. For example, if I just select artform: photography, I have to select other Inputs as well, because otherwise the Node gives me an output like this: 

![grafik](https://github.com/dagthomas/comfyui_dagthomas/assets/60526124/d53a9f15-2447-4864-b0da-16d92db12e10)

Maybe you can also have a look at the interdepending logic between the inputs. For example it might be interesting to just "photograph" without using a photographer. Or using the photo type without using "photograph" as artform.

Keep the good stuff coming :)

**Comment by dagthomas** [comment]
I have spent an hour on fixing them , should be better now :D also found out alot did not work as they should, thats what you get for coding blind, I guess. 

Have fixed it now, try it out - see if you get better results now!

**Comment by dxnxz** [comment]
haha, happens to me all the time :) Thanks! Will check out soon. cheers
